2013/08/23 01:38:47 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
2013/08/23 01:39:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
2013/08/23 01:39:53 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
2013/08/23 01:40:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
2013/08/23 01:40:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/default/ind...')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/default/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii
---
2013/08/23 01:40:49 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
2013/08/23 01:40:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii&password=
---
2013/08/23 01:46:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
2013/08/23 20:06:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:09:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:17:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:17:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:19:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:20:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:22:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:26:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'testdrive'' in /alidata/www/phpwind/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /alidata/www/phpwind/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /alidata/www/phpwind/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /alidata/www/phpwind/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /alidata/www/phpwind/yii/framework/web/CFormModel.php(39): CrudCode->init()
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/default/index
---
2013/08/23 20:40:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to find the code you requested.' in /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php:90
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionCode()
#1 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#2 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#3 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#4 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('code')
#5 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/controller/...')
#6 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#7 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#8 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/controller/code&id=1
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/controller/index
---
2013/08/23 20:47:52 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdriver.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /alidata/www/phpwind/yii/testdriver/index.php (13)
2013/08/23 20:47:52 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "user" cannot be found in the database.' in /alidata/www/phpwind/yii/framework/db/ar/CActiveRecord.php:2362
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(user))
#1 /alidata/www/phpwind/yii/framework/db/ar/CActiveRecord.php(138): CActiveRecord->getMetaData()
#2 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(66): CActiveRecord->__get('tableSchema')
#3 /alidata/www/phpwind/yii/framework/validators/CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#4 /alidata/www/phpwind/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#5 /alidata/www/phpwind/yii/framework/base/CModel.php(159): CValidator->validate(Object(CrudCode), NULL)
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(159): CModel->validate()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/crud/index
---
2013/08/23 20:48:25 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdriver.user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `user`.
in /alidata/www/phpwind/yii/testdriver/index.php (13)
2013/08/23 20:48:25 [error] [exception.CDbException] exception 'CDbException' with message 'The table "user" for active record class "user" cannot be found in the database.' in /alidata/www/phpwind/yii/framework/db/ar/CActiveRecord.php:2362
Stack trace:
#0 /alidata/www/phpwind/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(user))
#1 /alidata/www/phpwind/yii/framework/db/ar/CActiveRecord.php(138): CActiveRecord->getMetaData()
#2 /alidata/www/phpwind/yii/framework/gii/generators/crud/CrudCode.php(66): CActiveRecord->__get('tableSchema')
#3 /alidata/www/phpwind/yii/framework/validators/CInlineValidator.php(42): CrudCode->validateModel('model', Array)
#4 /alidata/www/phpwind/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(CrudCode), 'model')
#5 /alidata/www/phpwind/yii/framework/base/CModel.php(159): CValidator->validate(Object(CrudCode), NULL)
#6 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(159): CModel->validate()
#7 /alidata/www/phpwind/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /alidata/www/phpwind/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /alidata/www/phpwind/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /alidata/www/phpwind/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii/crud/index
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=gii/crud/index
---
2013/08/23 21:05:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "views/posts/_search".' in /alidata/www/phpwind/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('views/posts/_se...')
#1 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/testdriver/index.php?r=views/posts/_search
---
2013/08/23 21:05:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "_search".' in /alidata/www/phpwind/yii/framework/web/CController.php:483
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(270): CController->missingAction('_search')
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('_search')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('posts/_search')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=posts/_search
---
2013/08/23 21:05:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "views/posts/_search".' in /alidata/www/phpwind/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('views/posts/_se...')
#1 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/testdriver/index.php?r=views/posts/_search
---
2013/08/23 21:06:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /alidata/www/phpwind/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /alidata/www/phpwind/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /alidata/www/phpwind/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /alidata/www/phpwind/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /alidata/www/phpwind/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /alidata/www/phpwind/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /alidata/www/phpwind/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('posts/admin')
#9 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/yii/testdriver/index.php?r=posts/admin
HTTP_REFERER=http://42.120.9.9/yii/testdriver/index.php?r=site/login
---
2013/08/24 11:49:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /alidata/www/phpwind/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /alidata/www/phpwind/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /alidata/www/phpwind/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /alidata/www/phpwind/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /alidata/www/phpwind/yii/testdriver/index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yii/testdriver/index.php?r=gii
---
